In [ ]:
import numpy as np

## Arithmetic Operations with NumPy Arrays

Define a 2rowsx3columns array, called arr, with the sequence of values from 1 to 6.

In [ ]:
arr = np.arange(1,7).reshape(2,3)
arr

array([[1, 2, 3],
       [4, 5, 6]])

Calculate the power of two for each element and save the output array:

In [ ]:
arrP2 = arr*arr
arrP2

array([[ 1,  4,  9],
       [16, 25, 36]])

Compute the sum:

In [ ]:
np.sum(arrP2)

91

Scale the student quiz grades to 1-100 range:

In [ ]:
grades1 = np.array([1, 4, 3, 2, 5, 3, 2, 4, 1, 5])

In [ ]:
grades1*100/5

array([ 20.,  80.,  60.,  40., 100.,  60.,  40.,  80.,  20., 100.])

Compare the grades1 with grades2:

In [ ]:
grades2 = np.array([4, 3, 3, 1, 5, 4, 2, 2, 3, 5])

In [ ]:
grades1 > grades2

array([False,  True, False,  True, False, False, False,  True, False,
       False])

## Indexing and Slicing



### One-dimensional array

Define a 1-D array with values ranging between 0-9.

In [ ]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Select the first five elements:

In [ ]:
arr[:5]

array([0, 1, 2, 3, 4])

Select the elements between the 3rd and 7th indices:

In [ ]:
arr[3:7]

array([3, 4, 5, 6])

Select every other element, starting at index 1:

In [ ]:
arr[1::2]

array([1, 3, 5, 7, 9])

### Two-dimensional array

Define a 2-D array 4x6 array, with the sequence of values from 1 to 24.

In [ ]:
arr = np.arange(1,25).reshape(4,6)
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

Select the first two rows, first three columns:

In [ ]:
arr[:2,:3]

array([[1, 2, 3],
       [7, 8, 9]])

Select the last three rows, first 2 colums:

In [ ]:
arr[1:, :2]

array([[ 7,  8],
       [13, 14],
       [19, 20]])

Select every other row starting from index 2:

In [ ]:
arr[2::2]

array([[13, 14, 15, 16, 17, 18]])

Select all rows, every other column:

In [ ]:
arr[:, ::2]

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17],
       [19, 21, 23]])

## Boolean Indexing

In [ ]:
students = np.array(['A', 'C', 'C', 'B', 'A', 'A', 'C', 'B', 'B'])
students

array(['A', 'C', 'C', 'B', 'A', 'A', 'C', 'B', 'B'], dtype='<U1')

In [ ]:
np.random.seed(10)
quizTrials = np.random.rand(9,4)
quizTrials

array([[0.77132064, 0.02075195, 0.63364823, 0.74880388],
       [0.49850701, 0.22479665, 0.19806286, 0.76053071],
       [0.16911084, 0.08833981, 0.68535982, 0.95339335],
       [0.00394827, 0.51219226, 0.81262096, 0.61252607],
       [0.72175532, 0.29187607, 0.91777412, 0.71457578],
       [0.54254437, 0.14217005, 0.37334076, 0.67413362],
       [0.44183317, 0.43401399, 0.61776698, 0.51313824],
       [0.65039718, 0.60103895, 0.8052232 , 0.52164715],
       [0.90864888, 0.31923609, 0.09045935, 0.30070006]])

Get the quiz trial data for student 'B'

In [ ]:
quizTrials[students == 'B']

array([[0.00394827, 0.51219226, 0.81262096, 0.61252607],
       [0.65039718, 0.60103895, 0.8052232 , 0.52164715],
       [0.90864888, 0.31923609, 0.09045935, 0.30070006]])

Get the quiz #3 data for student 'A'

In [ ]:
quizTrials[students == 'A', 2]

array([0.63364823, 0.91777412, 0.37334076])

Calculate the quiz score differences between student 'A' and 'C':

In [ ]:
diffAC = quizTrials[students == 'A'] - quizTrials[students == 'C']
diffAC

array([[ 0.27281363, -0.2040447 ,  0.43558537, -0.01172683],
       [ 0.55264448,  0.20353625,  0.2324143 , -0.23881756],
       [ 0.10071119, -0.29184395, -0.24442622,  0.16099537]])

Change the negative values to -1, positive values to 1:

In [ ]:
diffAC[diffAC > 0] = 1
diffAC[diffAC < 0] = -1
diffAC

array([[ 1., -1.,  1., -1.],
       [ 1.,  1.,  1., -1.],
       [ 1., -1., -1.,  1.]])

## Expressing Conditional Logic as Array Operations

In [ ]:
students = np.array(['A', 'C', 'C', 'B', 'A', 'A', 'C', 'B', 'B'])
students

array(['A', 'C', 'C', 'B', 'A', 'A', 'C', 'B', 'B'], dtype='<U1')

In [ ]:
np.random.seed(10)
quizTrials = np.random.rand(9,4)
quizTrials

array([[0.77132064, 0.02075195, 0.63364823, 0.74880388],
       [0.49850701, 0.22479665, 0.19806286, 0.76053071],
       [0.16911084, 0.08833981, 0.68535982, 0.95339335],
       [0.00394827, 0.51219226, 0.81262096, 0.61252607],
       [0.72175532, 0.29187607, 0.91777412, 0.71457578],
       [0.54254437, 0.14217005, 0.37334076, 0.67413362],
       [0.44183317, 0.43401399, 0.61776698, 0.51313824],
       [0.65039718, 0.60103895, 0.8052232 , 0.52164715],
       [0.90864888, 0.31923609, 0.09045935, 0.30070006]])

Mark quiz scores which are above 0.5 as 1 and the rest as 0.

In [ ]:
quizTrials = np.where(quizTrials > 0.5, 1, 0)
quizTrials

array([[1, 0, 1, 1],
       [0, 0, 0, 1],
       [0, 0, 1, 1],
       [0, 1, 1, 1],
       [1, 0, 1, 1],
       [1, 0, 0, 1],
       [0, 0, 1, 1],
       [1, 1, 1, 1],
       [1, 0, 0, 0]])

FInd the number times student B got above 0.5 in the last quiz:

In [ ]:
quizTrials[students == 'B', 3].sum()

2