In [ ]:
import numpy as np

## Generating Dataset 

Our dataset will be page view dataset where column represents the days (DAY 1 to DAY 5), and the row represents the students who visits the pages. (Students array will be added later.)

#### TASK 1 [+4]. 
Generate a random array with values ranging between 0-1000. The array should have 10 rows and 5 columns. 

**Use the seed of 5** so that it will always generate the same set of random numbers.

In [ ]:
np.random.seed(5) # seed for reproducibility
arr1 = np.random. randint(1000, size=(10, 5)) # Two-dimensional array
arr1

array([[867, 206, 701, 998, 118],
       [400,  73,   8, 740, 743],
       [958, 411, 624, 670, 720],
       [519, 204, 911, 113, 437],
       [999,  80,  27,  44, 205],
       [715,  65, 431, 542, 980],
       [ 86, 637, 146, 254, 377],
       [649, 362,  41, 446, 897],
       [210, 103, 144, 974,   5],
       [826, 768, 976, 900, 110]])

## Slicing
In the following four task, you will apply slicing/indexing on the dataset.

#### TASK 2 [+4]. 

Select first 5 rows:

In [ ]:
arr1[:5,]

array([[867, 206, 701, 998, 118],
       [400,  73,   8, 740, 743],
       [958, 411, 624, 670, 720],
       [519, 204, 911, 113, 437],
       [999,  80,  27,  44, 205]])

#### TASK 3 [+4]. 

Select last 2 columns:

In [ ]:
arr1[:,3:]

array([[998, 118],
       [740, 743],
       [670, 720],
       [113, 437],
       [ 44, 205],
       [542, 980],
       [254, 377],
       [446, 897],
       [974,   5],
       [900, 110]])

#### TASK 4 [+4]. 

Select the 3rd and 4th row, and 2nd and 3rd columns:

In [ ]:
arr1[2:4,1:3]

array([[411, 624],
       [204, 911]])

## Boolean Indexing

Assume that the rows in pageViews array correspond to specific students given in the following array:

In [ ]:
students = np.array(['A', 'B','C', 'D', 'E', 'F', 'G', 'H', 'I', 'J'])
students

array(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J'], dtype='<U1')

#### TASK 5 [+6]. 
Find the visits of students D and H:

In [ ]:
arr1[(students == 'H') | (students == 'D')]

array([[519, 204, 911, 113, 437],
       [649, 362,  41, 446, 897]])

#### TASK 6 [+8]. 
Find the visits of students B and F during the first three days:

In [ ]:
arr2 = arr1[:,0:3]
arr2[(students == 'B') | (students == 'F')]

array([[400,  73,   8],
       [715,  65, 431]])

#### TASK 7 [+10]. 
Find all students' visits except student C and H:

In [ ]:
arr1[(students != 'C') & (students != 'H')]


array([[867, 206, 701, 998, 118],
       [400,  73,   8, 740, 743],
       [519, 204, 911, 113, 437],
       [999,  80,  27,  44, 205],
       [715,  65, 431, 542, 980],
       [ 86, 637, 146, 254, 377],
       [210, 103, 144, 974,   5],
       [826, 768, 976, 900, 110]])

## Calculating Basic Stats

#### TASK 8 [+5]. 
Compute the daily average across all students. Here you can use **[np.average](https://numpy.org/doc/stable/reference/generated/numpy.average.html)** . Be careful with the axis value.

In [ ]:
ar = np.average(arr1, axis = 0)
ar

array([622.9, 290.9, 400.9, 568.1, 459.2])

#### TASK 9 [+5]. 
Compute the average per student across all days. Here you can use **[np.average](https://numpy.org/doc/stable/reference/generated/numpy.average.html)** . Be careful with the axis value.

In [ ]:
av = np.average(arr1, axis = 1)
av

array([578. , 392.8, 676.6, 436.8, 271. , 546.6, 300. , 479. , 287.2,
       716. ])

#### TASK 10 [+15]. 
Return the name of the student (which is a letter) who have the lowest average page views. Here you should use [argmin](https://numpy.org/doc/stable/reference/generated/numpy.argmin.html) function.

In [ ]:
from numpy.core.fromnumeric import argmin
students[np.argmin(av)]

'E'

#### TASK 11 [+15]. 
Find the number of days student A visited more pages than student D.

In [ ]:
list_ = arr1[(students == 'A')] > arr1[(students == 'D')]
number_of_days =0
for i in list_:
  for j in i:
    if j==True:
      number_of_days+=1
number_of_days


3

#### TASK 12 [+20]. 

Return the list of students whose total visits until the 4th day (that is 1st, 2nd and 3rd days) is less than their visits on the 4th day.

In [ ]:
arr2 = np.cumsum (arr1[:,:4], axis = 1)
arr2 = arr2[:, 2:3]
arr3 = arr1[:, 3:4]
#print(arr2)
#print(arr3)
#print(arr2 < arr3)
arr4 = arr2 < arr3
numb = 0
for ii in range(len(arr4)):
  if arr4[ii]==True:
    print(students[ii])

  

B
I
